<a href="https://colab.research.google.com/github/RealB1ackY/MIREA_PyTorch/blob/main/Deep_learning_homework_1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [170]:
import torch
torch.__version__ 

'1.12.1+cu113'

ДЗ_01: neuron(neuron(1 * x1 + 1 * x2 - 0) - neuron(1 * x1 + 1 * x2 - 1))

In [171]:
torch.cuda.is_available()

True

In [172]:
Xs = torch.tensor([[1,1], [1, 0], [0, 1], [0, 0]], dtype=torch.float32)
Xy = torch.tensor([[0], [1], [1], [0]], dtype=torch.float32)

In [173]:
from torch import nn
from torch.optim import Adam


class XORModel(nn.Module):
  def __init__(self):
    super().__init__()
    self.layers = nn.Sequential(
        nn.Linear(2, 2),
        nn.Sigmoid(),
        nn.Linear(2, 1),
        nn.Sigmoid()
    )
    self.optimizer = Adam(self.parameters())
    self.loss = nn.MSELoss()

  def forward(self, X):
    return self.layers(X)

  def fit(self, X, y_true):
    self.optimizer.zero_grad()
    y_pred = self.forward(X)
    loss = self.loss(y_true, y_pred)
    loss.backward()
    self.optimizer.step()
    return loss.item()


In [174]:
xor_model = XORModel()

In [175]:
xor_model(Xs)

tensor([[0.3370],
        [0.3192],
        [0.3377],
        [0.3195]], grad_fn=<SigmoidBackward0>)

In [176]:
EPOCHS = 100000
for i in range(EPOCHS):
  if i % 1000 == 0:
    loss = xor_model.fit(Xs, Xy)
    print(loss)

0.27943775057792664
0.2792511582374573
0.27906495332717896
0.27887922525405884
0.2786939740180969
0.2785091996192932
0.2783248722553253
0.278141051530838
0.2779577374458313
0.2777749300003052
0.27759265899658203
0.2774108946323395
0.2772296667098999
0.2770489752292633
0.27686887979507446
0.2766893208026886
0.2765103280544281
0.27633190155029297
0.2761540710926056
0.27597683668136597
0.2758001685142517
0.27562415599823
0.2754487097263336
0.275273859500885
0.2750996947288513
0.27492615580558777
0.274753212928772
0.2745809257030487
0.27440929412841797
0.2742382287979126
0.2740679085254669
0.2738981544971466
0.273729145526886
0.2735607624053955
0.27339303493499756
0.2732260525226593
0.2730596661567688
0.2728939950466156
0.27272897958755493
0.2725646495819092
0.27240100502967834
0.2722380757331848
0.2720758318901062
0.2719142436981201
0.2717534005641937
0.27159324288368225
0.2714337408542633
0.27127498388290405
0.2711169421672821
0.2709595263004303
0.27080291509628296
0.27064695954322815
0.

ДЗ_02:

In [177]:
import torch


a = torch.tensor([2.0], requires_grad=True)
b = torch.tensor([4.0], requires_grad=True)
c = torch.tensor([1.0], requires_grad=True)
d = torch.tensor([5.0], requires_grad=False)

In [178]:
print(a.grad)

None


In [179]:
loss = a * b + c * d
loss.backward()

In [180]:
print(a.grad)
print(b.grad)
print(c.grad)
print(d.grad)

tensor([4.])
tensor([2.])
tensor([5.])
None
