<a href="https://colab.research.google.com/github/RealB1ackY/MIREA_PyTorch/blob/main/Deep_learning_homework_1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import torch
torch.__version__ 

'1.12.1+cu113'

ДЗ_01: neuron(neuron(1 * x1 + 1 * x2 - 0) - neuron(1 * x1 + 1 * x2 - 1))

In [2]:
torch.cuda.is_available()

True

In [51]:
Xs = torch.tensor([[1,1], [1, 0], [0, 1], [0, 0]], dtype=torch.float32)
Xy = torch.tensor([[1], [0], [1], [0]], dtype=torch.float32)

In [76]:
from torch import nn
from torch.optim import Adam


class XORModel(nn.Module):
  def __init__(self):
    super().__init__()
    self.layers = nn.Sequential(
        nn.Linear(2, 2),
        nn.Sigmoid(),
        nn.Linear(2, 1),
        nn.Sigmoid()
    )
    self.optimizer = Adam(self.parameters())
    self.loss = nn.MSELoss()

  def forward(self, X):
    return self.layers(X)

  def fit(self, X, y_true):
    self.optimizer.zero_grad()
    y_pred = self.forward(X)
    loss = self.loss(y_true, y_pred)
    loss.backward()
    self.optimizer.step()
    return loss.item()


In [77]:
xor_model = XORModel()

In [78]:
xor_model(Xs)

tensor([[0.6867],
        [0.6869],
        [0.6526],
        [0.6538]], grad_fn=<SigmoidBackward0>)

In [87]:
EPOCHS = 100000
for i in range(EPOCHS):
  if i % 1000 == 0:
    loss = xor_model.fit(Xs, Xy)
    print(loss)

7.890719327940943e-11
7.890658959563979e-11
7.890602754523357e-11
7.890546549482735e-11
7.890475078875525e-11
7.890418873834903e-11
7.89035850545794e-11
7.890302300417318e-11
7.890241932040354e-11
7.890178094216438e-11
7.890117725839474e-11
7.890060826909462e-11
7.89000531575823e-11
7.889940784044924e-11
7.88988041566796e-11
7.889817271733435e-11
7.889756903356471e-11
7.889700004426459e-11
7.889632697155591e-11
7.889580655451311e-11
7.889515429848615e-11
7.889455755361041e-11
7.88939955032042e-11
7.889335712496504e-11
7.88927534411954e-11
7.889214975742576e-11
7.88915113791866e-11
7.889094932878038e-11
7.88902762560717e-11
7.888970726677158e-11
7.888914521636536e-11
7.88884998992323e-11
7.888783376541753e-11
7.888727171501131e-11
7.888666109234777e-11
7.888614067530497e-11
7.888546066370239e-11
7.888485697993275e-11
7.888429492952653e-11
7.88836981846508e-11
7.888309450088116e-11
7.888253245047494e-11
7.888181774440284e-11
7.88812140606332e-11
7.888064507133308e-11
7.888008302092686e-1

ДЗ_02:

In [163]:
import torch


a = torch.tensor([2.0], requires_grad=True)
b = torch.tensor([4.0], requires_grad=True)
c = torch.tensor([1.0], requires_grad=True)
d = torch.tensor([5.0], requires_grad=False)

In [164]:
print(a.grad)

None


In [168]:
loss = a * b + c * d
loss.backward()

In [169]:
print(a.grad)
print(b.grad)
print(c.grad)
print(d.grad)

tensor([8.])
tensor([4.])
tensor([10.])
None
